// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Display: typeof import('./src/components/Display.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LayerLink: typeof import('./src/components/LayerLink.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Matrix: typeof import('./src/components/Matrix.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Solve: typeof import('./src/components/Solve.vue')['default']
    StartMatrix: typeof import('./src/components/StartMatrix.vue')['default']
    TargetMatrix: typeof import('./src/components/TargetMatrix.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
  }
}
